# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-07 13:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=40, verbose_name='شماره همراه')),
                ('fullname', models.CharField(max_length=40, verbose_name='نام کامل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40, verbose_name='نام کامل')),
                ('mobile_number', models.CharField(max_length=40, verbose_name='شماره همراه')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivers', to=settings.AUTH_USER_MODEL, verbose_name='مدیر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecyclingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('status', models.CharField(blank=True, choices=[('ثبت اطلاعات', 'ثبت اطلاعات'), ('تعیین پذیرنده', 'تعیین پذیرنده'), ('حذف درخواست', 'حذف درخواست')], default='ثبت اطلاعات', max_length=40, verbose_name='وضعیت')),
                ('trash_type', models.CharField(choices=[('خشک', 'خشک'), ('تر', 'تر'), ('کاغذ', 'کاغذ'), ('فلز', 'فلز')], default='خشک', max_length=40, verbose_name='نوع زباله')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.Receiver', verbose_name='دریافت کننده')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.MobileUser', verbose_name='درخواست دهنده')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
